name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Permiso para escribir en la rama gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # Tu código está en la raíz
          force_orphan: true       # Limpia la rama gh-pages en cada deploy
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
