name: Actualizar farmacias

on:
  schedule:
    - cron: "5 12 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: node scraper.js

      - run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add data.json historico.json
          git commit -m "update turnos" || echo "sin cambios"
          git push
